name: ScubaDoo
main: com.github.CubieX.ScubaDoo.ScubaDoo
author: CubieX
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit]
version: 1.0.2
description: Let players breath underwater

commands:
    scuba:
      description: Using ScubaDoo
      aliases: scu
      usage: /scuba version | reload | help

permissions:
    scubadoo.use:
        description: Allows using ScubaDoo
        default: op
    scubadoo.admin:
        description: Allows use of all commands
        default: op